### PR TITLE
CPS-8-get-tier-config (more)

### PR DESCRIPTION
**Pull request by JaviCerveraIngram**
Added methods to get TierConfigRequest and TierConfig objects by TCR, TC and TA ids.
 Made product id optional in requests and replaced dot notation with double underscore (since the former seems to have a bug).

### CODE REVIEW

**Comment by marcserrat** [comment]
From code perspective i'm OK. But we are on a fundamental question: Shall we implement such methods or force people to use generic listing that allows to pass filters like we have in PHP SDK?
From where this requirement comes? that will be interesting since we shall see if we implement it also on PHP SDK. At no case i want to have different logics on SDKs

**Comment by JaviCerveraIngram** [comment]
I added these because I think they express intent better than having to provide filters, which are after all an implementation detail that might change (for example, Vova told me that `__` in filter names will be replaced by `. `). This would allow the underlying SDK code to adapt to these changes without forcing modifications in the products.

Before, there was a method to get tier configuration when you have a TierAccount id (the one with TA- prefix), which is what you get in the asset tiers info. This PR pretends to cover other scenarios, for example:

We have implemented an action that receives a TierConfig id in the JWT (the one with TC- prefix). The changes made here let you cover this and other situations:

- Get TierConfig with TA id: TierAccount.get_config
- Get TierConfigRequest with TA id: TierAccount.get_request
- Get TierConfig with TC id: TierConfig.get
- Get TierConfigRequest with TCR id: TierConfigRequest.get

Of course, you can use the list method of the appropiate resource passing it any filters that you want, but this seemed higher level and I think simplifies things.

**Comment by marcserrat** [comment]
I disagree on this approach. I don't like this custom methods that brings little to no value. Better to have generic getTierConfigs that you can pass filters. Also this kind of deviations of SDKs must be prevented and discussed in advance. I will ask Vova for his own opinion and the resolution will be either we implement in BOTH sdks or on none.

**Comment by JaviCerveraIngram** [comment]
I'll leave the `TierConfig.get` method that was in the SDK before then, adding the possibility to add additional filters as arguments.

**Comment by marcserrat** [comment]
TierConfig.get is also strange method and i think we shall implement it at the moment we have direct api for it. Also current implementation does not take into consideration what's the latest approved one, something key on business scenario to understand what are the last parameters applied to the TC.

**Comment by JaviCerveraIngram** [comment]
Shall I replace it with TierConfigRequest.get then?

**Comment by JaviCerveraIngram** [comment]
`TierConfigRequest.list` sounds better then if we have to return the entire list. But does it makes sense to have the `get` method to return only the first object in the list directly so we don't have to process the list ourselves?

**Comment by marcserrat** [comment]
it does not....since each of the obtained requests contains "how was the TC" at such moment......and depends of the business use case.....i am in favor of tierConfigRequest.list that you pass params and developer must understand what he searches....when we ahve api to return "active" TC, then shall be implemented......but not now

**Comment by JaviCerveraIngram** [comment]
Uhmm then maybe we don't need to add it, since the SDK already would allow to get the list like this:

```
automation = TierConfigAutomation()
filters = automation.filters(
    status='approved',
    configuration__id='TC-686-193-035',
    configuration__product__id='PRD-376-646-770'
)
tier_requests = automation.list(filters)
```

While the TierConfigRequest.list method could be used to make the code much less verbose, I think that by now, the best approach will be to probably just remove the deprecation mark from ``FulfillmentAutomation.get_tier_config``, since it was already in the SDK to provide backwards compatibility and not add anything new.

**Comment by marcserrat** [comment]
OK

**Comment by JaviCerveraIngram** [comment]
I would like it more that way, but the way it currently works it that list() receives a dictionary with the filters, and if I change it to pass the filters as arguments, it would break compatibility with several packages we have already finished :(

**Comment by JaviCerveraIngram** [comment]
Although I could review and update all of them if you prefer to change it.

**Comment by JaviCerveraIngram** [comment]
Ok, I'll better close the PR now and leave everything as it was in v16.0. I don't want to break anything that was added in v16.0.

**Pull request closed without merging**
